### PR TITLE
Ocr test

### PR DESCRIPTION
**Pull request by mouchqi**
####this pull request is linked to the problem of classification, and using this lines of codes can classify the picturs already detected

### CODE REVIEW

**Review by rupert-sch — COMMENTED** [review]
Thanks for sharing OCRTraining.py! I tried it:

- It reads pictures from 'myData/*/*'. Could you please share your training data for reference?
- Line 7: Is it correct to use "flatten" with initial letter in lowercase? Is it necessary? "Flatten" is imported in line 4, too
- My installation (ubuntu 22.04) does not find keras.optimizer_v1 and I also could not find any hint searching the internet. Which module contains it? 
I installed several modules using 
```
pip install --upgrade pip
pip install Keras Tensorflow Sklearn Matplotlib
```
Thank you & Best regards
Rupert

**Comment by mouchqi** [comment]
yes of course I did it you can check now 
thank you for your attention

**Comment by goncalopp** [comment]
Thanks mouchqi. It looks like tests/OCRTraining.py is still there?

**Comment by mouchqi** [comment]
you can check now that the file is in Example and not in tests

**Comment by goncalopp** [comment]
All looks good, thank you for the contribution!

**Pull request merged**
